alllabels = {'A_lens':'A_{lens}', 'r_tensor':'r', 'beta_d':'\\beta_d', 'epsilon_ds':'\epsilon', 'birefringence':'\\theta',
             'alpha_d_ee':'\\alpha^{EE}_d', 'amp_d_ee':'A^{EE}_d', 'alpha_d_bb':'\\alpha^{BB}_d', 
             'amp_d_bb':'A^{BB}_d', 'beta_s':'\\beta_s', 'alpha_s_ee':'\\alpha^{EE}_s', 
             'amp_s_ee':'A^{EE}_s', 'alpha_s_bb':'\\alpha^{BB}_s', 'amp_s_bb':'A^{BB}_s', 
             'amp_d_eb':'A^{EB}_d', 'alpha_d_eb':'\\alpha^{EB}_d', 'amp_s_eb':'A^{EB}_s', 
             'alpha_s_eb':'\\alpha^{EB}_s', 'decorr_amp_d':'\Delta_d', 'decorr_amp_s':'\Delta_s', 
             'gain_1':'G_1', 'gain_2':'G_2', 'gain_3':'G_3', 'gain_4':'G_4', 'gain_5':'G_5', 'gain_6':'G_6',
             'gain_7':'G_7', 'gain_8':'G_8', 'gain_9':'G_9', 'gain_10':'{G_10}', 'gain_11':'{G_11}', 'gain_12':'{G_12}',
             'shift_1':'\Delta\\nu_1', 'shift_2':'\Delta\\nu_2', 'shift_3':'\Delta\\nu_3', 
             'shift_4':'\Delta\\nu_4', 'shift_5':'\Delta\\nu_5', 'shift_6':'\Delta\\nu_6', 
             'shift_7':'\Delta\\nu_7', 'shift_8':'\Delta\\nu_8', 'shift_9':'\Delta\\nu_9', 
             'shift_10':'\Delta\\nu_{10}', 'shift_11':'\Delta\\nu_{11}', 'shift_12':'\Delta\\nu_{12}', 
             'angle_1':'\phi_1', 'angle_2':'\phi_2', 'angle_3':'\phi_3', 'angle_4':'\phi_4', 
             'angle_5':'\phi_5', 'angle_6':'\phi_6', 'dphi1_1':'\Delta\phi_1', 'dphi1_2':'\Delta\phi_2', 
             'dphi1_3':'\Delta\phi_3', 'dphi1_4':'\Delta\phi_4', 'dphi1_5':'\Delta\phi_5', 'dphi1_6':'\Delta\phi_6'}


allranges={'$r$': [-1.0, 1.0],
 '$A_{lens}$': [0.0, 2.0],
 '$\\beta_d$': [0.1, 10.0],
 '$A^{EE}_d$': [0.0, None],
 '$\\alpha^{EE}_d$': [-3.0, 1.0],
 '$A^{BB}_d$': [0.0, None],
 '$\\alpha^{BB}_d$': [-3.0, 1.0],
 '$A^{EB}_d$': [-100.0, 100.0],
 '$\\alpha^{EB}_d$': [-3.0, 1.0],
 '$\\epsilon$': [-1.0, 1.0],
 '$\\Delta_d$': [0.9, 1.1],
 '$\\beta_s$': [-10.0, 0.0],
 '$A^{EE}_s$': [0.0, None],
 '$\\alpha^{EE}_s$': [-3.0, 1.0],
 '$A^{BB}_s$': [0.0, None],
 '$\\alpha^{BB}_s$': [-3.0, 1.0],
 '$A^{EB}_s$': [-100.0, 100.0],
 '$\\alpha^{EB}_s$': [-3.0, 1.0],
 '$\\theta$': [-30., 30.], 
 '$\\Delta_s$': [0.9, 1.1]}

