# These parameters are accessible to all stages
chains_dir: &chains_dir "/mnt/users/eastonf/Jeffreys/BBPower/chains/all_channels/gaussian_fgs/moments_full/jeffreys_priors/{sim_id:04}"  ## YOUR OUTPUT DIRECTORY
data_dir: &data_dir "/mnt/users/eastonf/Jeffreys/BBPower/jeffreys-prior/data"  ## YOUR DATA DIRECTORY   
covar_sacc: &covar_sacc !path [*data_dir, cells_coadded_cov_r0_Alens1_baseline_optimistic.fits]

global:
    nside: 256
    compute_dell: True
    # Number of simulations to run (ignored if empty)
    sim_ids: [4,9,14,19,24,29,34,39,44,49,54,59,64,69,74,79,84,89,94,99] # 0,19
    # Path where copy of config file will be stored
    config_copy: !path [*chains_dir, config_copy.yaml]

    # Input data or sims
    # Input data or sims
    data:
        # Path to sacc file with cross-split power spectra
        cells_coadded: !path [*data_dir, "cells_coadded_{sim_id:04}.fits"]
        # Path to sacc file with noise power spectra
        cells_noise: null
        # Path to sacc file with null-test power spectra
        cells_null: null
        # Path to sacc file with fiducial power spectra
        cells_fiducial: null
        # Path to sacc file with best-fit power spectra
        cells_best_fit: !path [*chains_dir, cells_model.fits]
        # Path to sacc file with auto- and cross-bundle power spectra
        cells_coadded_total: null
        # Path to sacc file with cross-split power spectrum covariance
        cells_coadded_cov: *covar_sacc
    
    # These are the different frequency channels. Keywords must coincide with
    # the tracer names inside the sacc files.
    map_sets:
        band1:  # 27 GHz
            beam_file: null
        band2:  # 39 GHz
            beam_file: null
        band3:  # 93 GHz
            beam_file: null
        band4:  # 145 GHz
            beam_file: null
        band5:  # 225 GHz
            beam_file: null
        band6:  # 280 GHz
            beam_file: null

theory_params:
    CMB:
        cmb_templates:
        - !path [*data_dir, camb_lens_nobb.dat]
        - !path [*data_dir, camb_lens_r1.dat]
        A_lens: 1.
        r_tensor: 0.
    dust:
        beta_d: 1.59
        alpha_d_EE: -0.48
        alpha_d_BB: -0.44
        A_d_EE: 61.
        A_d_BB: 32.
        nu0_d: 353.
        T_d: 19.6
    synch:
        beta_s: -3.0
        alpha_s_EE: -0.79
        alpha_s_BB: -0.82
        A_s_EE: 3.4
        A_s_BB: 1.8
        nu0_s: 23.

BBCompSep:
    output_dir: *chains_dir
    # Sampler type (choose 'emcee', 'polychord', 'fisher', 'single_point' or 
    # 'timing')
    sampler: emcee
    predict_linearized: False
    predict_to_sacc: True
    # If you chose polychord:
    nlive: 50
    nrepeat: 50
    # If you chose emcee:
    nwalkers: 40
    n_iters: 6000
    # Resume sampling from earlier runs
    resume: True
    # Likelihood type (choose 'chi2' or 'h&l')
    likelihood_type: chi2
    # What is the starting point?
    r_init: 1.e-3
    # Which polarization channels do you want to include?
    pol_channels: ['B']
    # Scale cuts (will apply to all frequencies)
    l_min: 30
    l_max: 300

    # CMB model
    cmb_model:
        # Template power spectrum. Should contained the lensed power spectra
        # with r=0 and r=1 respectively.
        cmb_templates:
        - !path [*data_dir, camb_lens_nobb.dat]
        - !path [*data_dir, camb_lens_r1.dat]

        # Free parameters
        params:
            # tensor-to-scalar ratio
            # See below for the meaning of the different elements in the list.
            r_tensor: ['r_tensor', 'jeffreys', [0]]
            # Lensing amplitude
            A_lens: ['A_lens', 'jeffreys', [1.0]]

    # Foreground model
    fg_model:
        # Include moment parameters?
        use_moments: True
        moments_lmax: 300

        # Add one section per component. They should be called `component_X`,
        # starting with X=1
        component_1:
            # Name for this component
            name: Dust
            # Type of SED. Should be one of the classes stored in fgbuster.components
            # https://github.com/fgbuster/fgbuster/blob/master/fgbuster/component_model.py
            sed: Dust
            # Type of power spectra for all possible polarization channel combinations.
            # Any combinations not added here will be assumed to be zero.
            # The names should be one of the classes in bbpower/fgcls.py
            cl:
                EE: ClPowerLaw
                BB: ClPowerLaw
            # Parameters of the SED
            sed_parameters:
                # The key can be anything you want, but each parameter in the model
                # must have a different name.
                # The first item in the list is the name of the parameter used by fgbuster
                # The second item is the type of prior. The last item are the numbers
                # necessary to define the prior. They should be:
                #  - Gaussian: [mean,sigma]
                #  - tophat: [lower edge, start value, upper edge]
                #  - fixed: [parameter value]
                # nu0-type parameters can only be fixed.
                #beta_d: ['beta_d', 'fixed', [1.54]]
                beta_d: ['beta_d', 'jeffreys', [1.6]]
                temp_d: ['temp', 'fixed', [20.]]
                nu0_d: ['nu0', 'fixed', [353.]]
            cl_parameters:
                # Same for power spectrum parameters
                # (broken down by polarization channel combinations)
                EE:
                   amp_d_ee: ['amp', 'fixed', [56.]]
                   alpha_d_ee: ['alpha', 'fixed', [-0.32]]
                   l0_d_ee: ['ell0', 'fixed', [80.]]
                BB:
                   amp_d_bb: ['amp', 'jeffreys', [28.]] # 46.
                   alpha_d_bb: ['alpha', 'jeffreys', [-0.16]]
                   l0_d_bb: ['ell0', 'fixed', [80.]]
            # If this component should be correlated with any other, list them here
            cross:
                # In this case the list should contain:
                # [component name, prior type, prior parameters]
                epsilon_ds: ['component_2', 'jeffreys', [0.]]
            # Moment parameters. Only relevant if set "use_moments" to "True"
            moments:
                # Define gammas for varying spectral indices of components
                gamma_d_beta : ['gamma_beta', 'jeffreys', [-3.5]]
                amp_d_beta : ['amp_beta', 'jeffreys', [0.1]] # If Jeffreys Priors are used, cannot chose 0 as a starting point (since partials wrt gamma_s vanish)

        component_2:
            name: Synchrotron
            sed: Synchrotron
            cl:
                EE: ClPowerLaw
                BB: ClPowerLaw
            sed_parameters:
                beta_s: ['beta_pl', 'jeffreys', [-3.0]]
                #beta_s: ['beta_pl', 'fixed', [0.0]]
                nu0_s: ['nu0', 'fixed', [23.]]
            cl_parameters:
                EE:
                    #amp_s_ee: ['amp', 'tophat', [0., 4., "inf"]]
                    amp_s_ee: ['amp', 'tophat', [5., 9., 15.]]
                    alpha_s_ee: ['alpha', 'tophat', [-2., -0.7, 0.]]
                    l0_s_ee: ['ell0', 'fixed', [80.]]
                BB:
                    amp_s_bb: ['amp', 'jeffreys', [1.45]]  # 1.6
                    alpha_s_bb: ['alpha', 'jeffreys', [-0.7]]  # 0.-93
                    l0_s_bb: ['ell0', 'fixed', [80.]]
            # Moment parameters. Only relevant if set "use_moments" to "True"
            moments:
                # Define gammas for varying spectral indices of components
                gamma_s_beta : ['gamma_beta', 'jeffreys', [-3.5]]
                amp_s_beta : ['amp_beta', 'jeffreys', [0.1]] # If Jeffreys priors are used, cannot chose 0 as a starting point (since partials wrt gamma_s vanish)


BBPlotter:
    # MCMC chain file
    chain_file: !path [*chains_dir, emcee.npz]
    # chi2 npz file
    chi2_file: !path [*chains_dir, chi2.npz]

    # Output directory for plots
    plot_dir: !path [*chains_dir, plots]
    # HTML page with plots
    plots_page: !path [*chains_dir, plots_page.html]

    # Which polarization channels to plot
    pol_channels: ["B"]
    # Maximum and minimum ell between which things will be plotted
    lmin_plot: 30
    lmax_plot: 300
    # Add total coadds to C_ell plots?
    plot_cells_coadded_total: False
    # Add noise spectra to C_ell plots?
    plot_cells_noise: False
    # Plot null tests?
    plot_cells_null: False
    # Plot likelihood?
    plot_likelihood: True
    # List of parameters to plot
    params_plot: [r_tensor, A_lens, beta_d, amp_d_bb, alpha_d_bb, amp_d_beta, gamma_d_beta, beta_s, amp_s_bb, alpha_s_bb, amp_s_beta, gamma_s_beta, epsilon_ds]

    # "Truth" parameter values for plotting purposes
    truth:
        A_lens: 1
        r_tensor: 0
        beta_d: 1.54
        epsilon_ds: 0.
        alpha_d_bb: -0.16
        amp_d_bb: 28
        beta_s: -3.
        alpha_s_bb: -0.93
        amp_s_bb: 1.6
        gamma_d_beta: null
        amp_d_beta: 0
        gamma_s_beta: null
        amp_s_beta: 0